import { Phone } from '../types/phone';

// Image Imports

import GooglePixel6 from '../assets/images/GooglePixel6.jpg';
import GooglePixel6a from '../assets/images/GooglePixel6a.jpg';
import GooglePixel6Pro from '../assets/images/GooglePixel6Pro.jpg';
import GooglePixel7 from '../assets/images/GooglePixel7.jpg';
import GooglePixel7a from '../assets/images/GooglePixel7a.jpg';
import GooglePixel7Pro from '../assets/images/GooglePixel7Pro.jpg';
import GooglePixel8 from '../assets/images/GooglePixel8.jpg';
import GooglePixel8a from '../assets/images/Google Pixel 8a.jpg';
import GooglePixel8Pro from '../assets/images/GooglePixel8Pro.jpg';
import GooglePixel9 from '../assets/images/GooglePixel9.jpg';
import GooglePixel9Pro from '../assets/images/GooglePixel9Pro.jpg';
import GooglePixel9ProXL from '../assets/images/GooglePixel9ProXL.jpg';
import GooglePixel9ProFold from '../assets/images/GooglePixel9ProFold.jpg';
import GooglePixelFold from '../assets/images/GooglePixelFold.jpg';

import OnePlus10Pro from '../assets/images/OnePlus10Pro.jpg';
import OnePlus10T from '../assets/images/OnePlus10T.jpg';
import OnePlus12 from '../assets/images/OnePlus12.jpg';
import OnePlus12R from '../assets/images/OnePlus12R.jpg';
import OnePlus11 from '../assets/images/OnePlus11.jpg';
import OnePlusOpen from '../assets/images/OnePlusOpen.jpg';

import OppoFindN2Flip from '../assets/images/OppoFindN2Flip.jpg';
import OppoFindX5 from '../assets/images/OppoFindX5.jpg';
import OppoFindX5Lite from '../assets/images/OppoFindX5Lite.jpg';
import OppoFindX5Pro from '../assets/images/OppoFindX5Pro.jpg';
import OppoFindX8 from '../assets/images/OppoFindX8.jpg';
import OppoReno8 from '../assets/images/OppoReno8.jpg';
import OppoReno8Lite from '../assets/images/OppoReno8Lite.jpg';
import OppoReno8Pro from '../assets/images/OppoReno8Pro.jpg';
import OppoReno12 from '../assets/images/OppoReno12.jpg';
import OppoReno12F from '../assets/images/OppoReno12F.jpg';


import SonyXperia1III from '../assets/images/SonyXperia1III.jpg';
import SonyXperia1IV from '../assets/images/SonyXperia1IV.jpg';
import SonyXperia1V from '../assets/images/SonyXperia1V.jpg';
import SonyXperia1VI from '../assets/images/SonyXperia1VI.jpg';
import SonyXperia5II from '../assets/images/SonyXperia5II.jpg';
import SonyXperia5IV from '../assets/images/SonyXperia5IV.jpg';
import SonyXperia10III from '../assets/images/SonyXperia10III.jpg';
import SonyXperia10W from '../assets/images/SonyXperia10W.jpg';
import SonyXperia10V from '../assets/images/SonyXperia10V.jpg';
import SonyXperia10VI from '../assets/images/SonyXperia10VI.jpg';
import SonyXperiaProI from '../assets/images/SonyXperiaProI.jpg';


import XiaomiRedmiA3 from '../assets/images/XiaomiRedmiA3.jpg';
import XiaomiPocoM6 from '../assets/images/XiaomiPocoM6.jpg';
import XiaomiPocoX5 from '../assets/images/XiaomiPocoX5.jpg';
import XiaomiPocoX5Pro from '../assets/images/XiaomiPocoX5Pro.jpg';
import XiaomiPocoX6Pro from '../assets/images/XiaomiPocoX6Pro.jpg';
import XiaomiPocoX7 from '../assets/images/XiaomiPocoX7.jpg';
import XiaomiRedmi10C from '../assets/images/XiaomiRedmi10C.jpg';
import Xiaomi11T from '../assets/images/Xiaomi11T.jpg';
import Xiaomi11TPro from '../assets/images/Xiaomi11TPro.jpg';
import XiaomiRedmiNote11 from '../assets/images/XiaomiRedmiNote11.jpg';
import XiaomiRedmiNote11Pro5G from '../assets/images/XiaomiRedmiNote11Pro5G.jpg';
import Xiaomi12 from '../assets/images/Xiaomi12.jpg';
import XiaomiRedmi12C from '../assets/images/XiaomiRedmi12C.jpg';
import Xiaomi12Pro from '../assets/images/Xiaomi12Pro.jpg';
import XiaomiRedmi13C from '../assets/images/XiaomiRedmi13C.jpg';
import Xiaomi13T from '../assets/images/Xiaomi13T.jpg';
import Xiaomi13TPro from '../assets/images/Xiaomi13TPro.jpg';
import Xiaomi14 from '../assets/images/Xiaomi14.jpg';
import XiaomiRedmi14C from '../assets/images/XiaomiRedmi14C.jpg';
import Xiaomi14T from '../assets/images/Xiaomi14T.jpg';
import Xiaomi14Ultra from '../assets/images/Xiaomi14Ultra.jpg';
import Xiaomi15 from '../assets/images/Xiaomi15.jpg';
import Xiaomi15Pro from '../assets/images/Xiaomi15Pro.jpg';


import SamsungGalaxyA04 from '../assets/images/SamsungGalaxyA04.jpg';
import SamsungGalaxyA06 from '../assets/images/SamsungGalaxyA06.jpg';
import SamsungGalaxyA13 from '../assets/images/SamsungGalaxyA13.jpg';
import SamsungGalaxyA14 from '../assets/images/SamsungGalaxyA14.jpg';
import SamsungGalaxyA23 from '../assets/images/SamsungGalaxyA23.jpg';
import SamsungGalaxyA34 from '../assets/images/SamsungGalaxyA34.jpg';
import SamsungGalaxyA54 from '../assets/images/SamsungGalaxyA54.jpg';
import SamsungGalaxyC55 from '../assets/images/SamsungGalaxyC55.jpg';
import SamsungGalaxyF13 from '../assets/images/SamsungGalaxyF13.jpg';
import SamsungGalaxyF55 from '../assets/images/SamsungGalaxyF55.jpg';
import SamsungGalaxyM05 from '../assets/images/SamsungGalaxyM05.jpg';
import SamsungGalaxyM13 from '../assets/images/SamsungGalaxyM13.jpg';
import SamsungGalaxyM14 from '../assets/images/SamsungGalaxyM14.jpg';
import SamsungGalaxyM15 from '../assets/images/SamsungGalaxyM15.jpg';
import SamsungGalaxyM23 from '../assets/images/SamsungGalaxyM23.jpg';
import SamsungGalaxyM35 from '../assets/images/SamsungGalaxyM35.jpg';
import SamsungGalaxyM55 from '../assets/images/SamsungGalaxyM55.jpg';
import SamsungGalaxyS20FE from '../assets/images/SamsungGalaxyS20FE.jpg';
import SamsungGalaxyS23FE from '../assets/images/SamsungGalaxyS23FE.jpg';
import SamsungGalaxyS23Ultra from '../assets/images/SamsungGalaxyS23Ultra.jpg';
import SamsungGalaxyS24plus from '../assets/images/SamsungGalaxyS24Plus.jpg';
import SamsungGalaxyS24 from '../assets/images/SamsungGalaxyS24.jpg';
import SamsungGalaxyS24FE from '../assets/images/SamsungGalaxyS24FE.jpg';
import SamsungGalaxyS24Ultra from '../assets/images/SamsungGalaxyS24Ultra.jpg';
import SamsungGalaxyZFlip4 from '../assets/images/SamsungGalaxyZFlip4.jpg';
import SamsungGalaxyZFlip5 from '../assets/images/SamsungGalaxyZFlip5.jpg';
import SamsungGalaxyZFold4 from '../assets/images/SamsungGalaxyZFold4.jpg';
import SamsungGalaxyZFold5 from '../assets/images/SamsungGalaxyZFold5.jpg';
import SamsungGalaxyZFlip6 from '../assets/images/SamsungGalaxyZFlip6.jpg';
import SamsungGalaxyZFold6 from '../assets/images/SamsungGalaxyZFold6.jpg';


import MotorolaEdge40Pro from '../assets/images/Motorola Edge 40 Pro.jpg';
import MotorolaEdge40 from '../assets/images/Motorola Edge 40 Pro.jpg';
import MotorolaRazr40 from '../assets/images/Motorola Edge 40 Pro.jpg';

export const MOCK_PHONES: Phone[] = [
  // Google Phones
  {
    id: 'pixel-6-001',
    name: 'Google Pixel 6',
    brand: 'Google',
    price: 154,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel6,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2021
  },
  {
    id: 'pixel-6-002',
    name: 'Google Pixel 6a',
    brand: 'Google',
    price: 119,
    primaryCamera: '12MP',
    features: ['5G', 'Wireless charging', 'Fast charging'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel6a,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2021
  },
  {
    id: 'pixel-6-003',
    name: 'Google Pixel 6 Pro',
    brand: 'Google',
    price: 197,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel6Pro,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2021
  },
  {
    id: 'pixel-7-001',
    name: 'Google Pixel 7',
    brand: 'Google',
    price: 214,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel7,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022 
  },
  {
    id: 'pixel-7-002',
    name: 'Google Pixel 7a',
    brand: 'Google',
    price: 149,
    primaryCamera: '64MP',
    features: ['5G', 'Wireless charging'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel7a,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'pixel-7-003',
    name: 'Google Pixel 7 Pro',
    brand: 'Google',
    price: 233,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: 'Up to 24 hours',
    screenSize: 'Over 6.5"',
    imageUrl: GooglePixel7Pro,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'pixel-8-001',
    name: 'Google Pixel 8',
    brand: 'Google',
    price: 274,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel8,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'pixel-8-002',
    name: 'Google Pixel 8a',
    brand: 'Google',
    price: 214,
    primaryCamera: '64MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel8a,
    isNew: true,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'pixel-8-003',
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    price: 294,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: GooglePixel8Pro,
    isNew: false,
    dimensions: 'Large',
    storage: ['128GB'],
    ram: ['12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'pixel-9-001',
    name: 'Google Pixel 9',
    brand: 'Google',
    price: 529,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel9,
    isNew: true,
    dimensions: 'Large',
    storage: ['128GB'],
    ram: ['12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'pixel-9-002',
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    price: 685,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel9Pro,
    isNew: true,
    dimensions: 'Large',
    storage: ['128GB'],
    ram: ['16GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'pixel-9-003',
    name: 'Google Pixel 9 Pro XL',
    brand: 'Google',
    price: 734,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: '24-48 hours',
    screenSize: 'over 6.5"',
    imageUrl: GooglePixel9ProXL,
    isNew: true,
    dimensions: 'Large',
    storage: ['128GB'],
    ram: ['16GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'pixel-9-004',
    name: 'Google Pixel 9 Pro Fold',
    brand: 'Google',
    price: 1149,
    primaryCamera: '48MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixel9ProFold,
    isNew: true,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['16GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'pixel-fold',
    name: 'Google Pixel Fold',
    brand: 'Google',
    price: 469,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Water resistant'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: GooglePixelFold,
    isNew: false,
    dimensions: 'Standard',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  // One Plus Phones
  {
    id: 'Plus-10-01',
    name: 'OnePlus 10 Pro',
    brand: 'OnePlus',
    price: 254,
    primaryCamera: '50MP',
    features: ['5G',  'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: OnePlus10Pro,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2022
  },
  {
    id: 'Plus-10-02',
    name: 'OnePlus 10T',
    brand: 'OnePlus',
    price: 350,
    primaryCamera: '50MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: OnePlus10T,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2022 
  },
  {
    id: 'Plus-12-01',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    price: 628,
    primaryCamera: '50MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: OnePlus12,
    isNew: false,
    dimensions: 'Compact',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'HD+',
    releaseYear: 2023
  },
  {
    id: 'Plus-12-02',
    name: 'OnePlus 12R',
    brand: 'OnePlus',
    price: 499,
    primaryCamera: '50MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: OnePlus12R,
    isNew: true,
    dimensions: 'Compact',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2024
  },
  {
    id: 'Plus-11',
    name: 'OnePlus 11',
    brand: 'OnePlus',
    price: 599,
    primaryCamera: '50MP',
    features: ['5G', 'Dual SIM', 'Fast charging'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: OnePlus11,
    isNew: false,
    dimensions: 'standard',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2023
  },
  {
    id: 'Plus-Open',
    name: 'OnePlus Open',
    brand: 'OnePlus',
    price: 1021,
    primaryCamera: '64MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: OnePlusOpen,
    isNew: false,
    dimensions: 'Large',
    storage: ['512GB'],
    ram: ['16GB'],
    screenResolution: "4K",
    releaseYear: 2023
  },
  // Oppo Phones
  {
    id: 'Find-N',
    name: 'Oppo Find N2 Flip',
    brand: 'Oppo',
    price: 480,
    primaryCamera: '50MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: OppoFindN2Flip,
    isNew: false,
    dimensions: 'Standard',
    storage: ['256GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2022
  },
  {
    id: 'Find-X-1',
    name: 'Oppo Find X5',
    brand: 'Oppo',
    price: 1970,
    primaryCamera: '',
    features: ['Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: OppoFindX5,
    isNew: false,
    dimensions: 'standard',
    storage: ['128GB', '256GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2018
  },
  {
    id: 'Find-X-2',
    name: 'Oppo Find X5 Lite',
    brand: 'Oppo',
    price: 280,
    primaryCamera: '49MP - 108MP',
    features: ['Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: OppoFindX5Lite,
    isNew: false,
    dimensions: 'standard',
    storage: ['256GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2022
  },
  {
    id: 'Find-X-3',
    name: 'Oppo Find X5 Pro',
    brand: 'Oppo',
    price: 1086,
    primaryCamera: '49MP - 108MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant'],
    batteryLife: 'Over 48 hours',
    screenSize: 'over 6.5"',
    imageUrl: OppoFindX5Pro,
    isNew: false,
    dimensions: 'Large',
    storage: ['256GB', '512GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'Find-X-4',
    name: 'Oppo Find X8',
    brand: 'Oppo',
    price: 747,
    primaryCamera: '49MP - 108MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant'],
    batteryLife: 'Over 48 hours',
    screenSize: 'over 6.5"',
    imageUrl: OppoFindX8,
    isNew: true,
    dimensions: 'Large',
    storage: ['256GB', '512GB'],
    ram: ['12GB', '16GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'Reno-8-01',
    name: 'Oppo Reno 8',
    brand: 'Oppo',
    price: 649,
    primaryCamera: '49MP - 108MP',
    features: ['Fast charging', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: OppoReno8,
    isNew: false,
    dimensions: 'Large',
    storage: ['128GB', '256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'Reno-8-02',
    name: 'Oppo Reno 8 Lite',
    brand: 'Oppo',
    price: 260,
    primaryCamera: '49MP - 108MP',
    features: ['Fast charging', 'Dual SIM', 'Water resistance'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: OppoReno8Lite,
    isNew: false,
    dimensions: 'Large',
    storage: ['128GB', '256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'Reno-8-03',
    name: 'Oppo Reno 8 Pro',
    brand: 'Oppo',
    price: 260,
    primaryCamera: '49MP - 108MP',
    features: ['Fast charging', 'Dual SIM', 'Water resistance', '5G'],
    batteryLife: 'Over 48 hours',
    screenSize: 'over 6.5"',
    imageUrl: OppoReno8Pro,
    isNew: false,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'Reno-8-04',
    name: 'Oppo Reno 12',
    brand: 'Oppo',
    price: 370,
    primaryCamera: '49MP - 108MP',
    features: ['Fast charging', 'Dual SIM', 'Water resistance', '5G'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: OppoReno12,
    isNew: false,
    dimensions: 'Large',
    storage: ['256GB', '512GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2024
  },
  {
    id: 'Reno-8-05',
    name: 'Oppo Reno 12F',
    brand: 'Oppo',
    price: 360,
    primaryCamera: '49MP - 108MP',
    features: ['Fast charging', 'Dual SIM', 'Water resistance', '5G'],
    batteryLife: '24-48 hours',
    screenSize: 'over 6.5"',
    imageUrl: OppoReno12F,
    isNew: false,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  // Sony Xperia Phone
  {
    id: 'sony-01',
    name: 'Sony Xperia 10 III',
    brand: 'Sony',
    price: 655,
    primaryCamera: '12MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia10III,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['6GB'],
    screenResolution: 'HD+',
    releaseYear: 2021
  },
  {
    id: 'sony-02',
    name: 'Sony Xperia 10V',
    brand: 'Sony',
    price: 349,
    primaryCamera: '48MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 8.5"',
    imageUrl: SonyXperia10V,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2023
  },
  {
    id: 'sony-03',
    name: 'Sony Xperia 10VI',
    brand: 'Sony',
    price: 360,
    primaryCamera: '48MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: '0ver 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia10VI,
    isNew: true,
    dimensions: 'Compact',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'sony-04',
    name: 'Sony Xperia 10W',
    brand: 'Sony',
    price: 282,
    primaryCamera: '12MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia10W,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['6GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'sony-05',
    name: 'Sony Xperia 1 III',
    brand: 'Sony',
    price: 1049,
    primaryCamera: '12MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia1III,
    isNew: false,
    dimensions: 'Compact',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: "4K",
    releaseYear: 2021
  },
  {
    id: 'sony-06',
    name: 'Sony Xperia 1 IV',
    brand: 'Sony',
    price: 529,
    primaryCamera: '12MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia1IV,
    isNew: false,
    dimensions: 'Standard',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'sony-07',
    name: 'Sony Xperia 1 V',
    brand: 'Sony',
    price: 839,
    primaryCamera: '48MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia1V,
    isNew: false,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2023
  },
  {
    id: 'sony-08',
    name: 'Sony Xperia 1 VI',
    brand: 'Sony',
    price: 957,
    primaryCamera: '48MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia1VI,
    isNew: true,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2024
  },
  {
    id: 'sony-09',
    name: 'Sony Xperia 5 II',
    brand: 'Sony',
    price: 468,
    primaryCamera: '12MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia5II,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2020
  },
  {
    id: 'sony-10',
    name: 'Sony Xperia 5IV',
    brand: 'Sony',
    price: 798,
    primaryCamera: '12MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperia5IV,
    isNew: false,
    dimensions: 'Compact',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'QHD+',
    releaseYear: 2022
  },
  {
    id: 'sony-11',
    name: 'Sony Xperia PRO-I',
    brand: 'Sony',
    price: 856,
    primaryCamera: '12MP',
    features: ['5G', 'Dual SIM', 'Water resistant'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SonyXperiaProI,
    isNew: false,
    dimensions: 'Compact',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2022
  },
  // Xiaomi Phones
  {
    id: 'Redmi-01',
    name: 'Xiaomi 11T',
    brand: 'Xiaomi',
    price: 170,
    primaryCamera: '49MP - 108MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'over 6.5"',
    imageUrl: Xiaomi11T,
    isNew: false,
    dimensions: 'Large',
    storage: ['128GB', '256GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2021
  },
  {
    id: 'Redmi-02',
    name: 'Xiaomi 11T Pro',
    brand: 'Xiaomi',
    price: 165,
    primaryCamera: '49MP - 108MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'over 6.5"',
    imageUrl: Xiaomi11TPro,
    isNew: false,
    dimensions: 'Large',
    storage: ['128GB', '256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'HD+',
    releaseYear: 2021 
  },
  {
    id: 'Redmi-03',
    name: 'Xiaomi 12',
    brand: 'Xiaomi',
    price: 139,
    primaryCamera: '49MP - 108MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'over 6.5"',
    imageUrl: Xiaomi12,
    isNew: false,
    dimensions: 'Large',
    storage: ['128GB', '256GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2021
  },
  {
    id: 'Redmi-04',
    name: 'Xiaomi 12 Pro',
    brand: 'Xiaomi',
    price: 391,
    primaryCamera: '49MP - 108MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'over 6.5"',
    imageUrl: Xiaomi12Pro,
    isNew: false,
    dimensions: 'Large',
    storage: ['128GB', '256GB'],
    ram: ['8GB'],
    screenResolution: 'HD+',
    releaseYear: 2021
  },
  {
    id: 'Redmi-05',
    name: 'Xiaomi 13T',
    brand: 'Xiaomi',
    price: 399,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: Xiaomi13T,
    isNew: false,
    dimensions: 'Compact',
    storage: ['256GB'],
    ram: ['8GB'],
    screenResolution: 'QHD+',
    releaseYear: 2023
  },
  {
    id: 'Redmi-06',
    name: 'Xiaomi 13T Pro',
    brand: 'Xiaomi',
    price: 469,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: Xiaomi13TPro,
    isNew: false,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2023
  },
  {
    id: 'Redmi-07',
    name: 'Xiaomi 14',
    brand: 'Xiaomi',
    price: 546,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: Xiaomi14,
    isNew: true,
    dimensions: 'Compact',
    storage: ['128GB', '256GB'],
    ram: ['6GB', '8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'Redmi-08',
    name: 'Xiaomi 14T',
    brand: 'Xiaomi',
    price: 525,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: Xiaomi14T,
    isNew: true,
    dimensions: 'Large',
    storage: ['512GB'],
    ram: ['12GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  {
    id: 'Redmi-09',
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    price: 1035,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: Xiaomi14Ultra,
    isNew: true,
    dimensions: 'Large',
    storage: ['312GB'],
    ram: ['12GB', '16GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  {
    id: 'Redmi-10',
    name: 'Xiaomi 15',
    brand: 'Xiaomi',
    price: 1165,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: Xiaomi15,
    isNew: true,
    dimensions: 'Large',
    storage: ['512GB'],
    ram: ['12GB', '16GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  {
    id: 'Redmi-11',
    name: 'Xiaomi 15 Pro',
    brand: 'Xiaomi',
    price: 1328,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: Xiaomi15Pro,
    isNew: true,
    dimensions: 'Large',
    storage: ['512GB'],
    ram: ['12GB', '16GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  {
    id: 'Redmi-12',
    name: 'Xiaomi Poco M6',
    brand: 'Xiaomi',
    price: 231,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiPocoM6,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['4GB'],
    screenResolution: 'HD+',
    releaseYear: 2022
  },
  {
    id: 'Redmi-13',
    name: 'Xiaomi Poco X5',
    brand: 'Xiaomi',
    price: 220,
    primaryCamera: '48MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiPocoX5,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['6GB'],
    screenResolution: 'HD+',
    releaseYear: 2023
  },
  {
    id: 'Redmi-14',
    name: 'Xiaomi Poco X5 Pro',
    brand: 'Xiaomi',
    price: 295,
    primaryCamera: '108MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiPocoX5Pro,
    isNew: false,
    dimensions: 'Compact',
    storage: ['256GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'Redmi-15',
    name: 'Xiaomi Poco X6 Pro',
    brand: 'Xiaomi',
    price: 284,
    primaryCamera: '64MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiPocoX6Pro,
    isNew: true,
    dimensions: 'Standard',
    storage: ['256GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'Redmi-16',
    name: 'Xiaomi Poco X7',
    brand: 'Xiaomi',
    price: 304,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiPocoX7,
    isNew: true,
    dimensions: 'Standard',
    storage: ['256GB'],
    ram: ['8GB'],
    screenResolution: 'QHD+',
    releaseYear: 2025
  },
  {
    id: 'Redmi-17',
    name: 'Xiaomi Redmi 10C',
    brand: 'Xiaomi',
    price: 129,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiRedmi10C,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['3GB', '4GB'],
    screenResolution: 'HD+',
    releaseYear: 2022
  },
  {
    id: 'Redmi-18',
    name: 'Xiaomi Redmi 12C',
    brand: 'Xiaomi',
    price: 129,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiRedmi12C,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['3GB'],
    screenResolution: 'HD+',
    releaseYear: 2022
  },
  {
    id: 'Redmi-19',
    name: 'Xiaomi Redmi 13C',
    brand: 'Xiaomi',
    price: 87,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiRedmi13C,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['4GB', '8GB'],
    screenResolution: 'HD+',
    releaseYear: 2023
  },
  {
    id: 'Redmi-20',
    name: 'Xiaomi Redmi 14C',
    brand: 'Xiaomi',
    price: 111,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiRedmi14C,
    isNew: true,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['4GB', '8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'Redmi-21',
    name: 'Xiaomi Redmi A3',
    brand: 'Xiaomi',
    price: 80,
    primaryCamera: '8MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiRedmiA3,
    isNew: true,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['3GB'],
    screenResolution: 'HD+',
    releaseYear: 2024
  },
  {
    id: 'Redmi-22',
    name: 'Xiaomi Redmi Note 11',
    brand: 'Xiaomi',
    price: 204,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: XiaomiRedmiNote11,
    isNew: false,
    dimensions: 'Cpmpact',
    storage: ['128GB'],
    ram: ['6GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'Redmi-23',
    name: 'Xiaomi Redmi Note 11 Pro 5G',
    brand: 'Xiaomi',
    price: 199,
    primaryCamera: '108MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: XiaomiRedmiNote11Pro5G,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB', '128GB'],
    ram: ['6GB', '8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  // Samsung Phones
  {
    id: 'samsung-01',
    name: 'Samsung Galaxy A04',
    brand: 'Samsung',
    price: 74,
    primaryCamera: '50MP',
    features: ['Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SamsungGalaxyA04,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['4GB'],
    screenResolution: 'FHD+',
    releaseYear: 2021
  },
  {
    id: 'samsung-02',
    name: 'Samsung Galaxy A06',
    brand: 'Samsung',
    price: 89, 
    primaryCamera: '50MP',
    features: ['Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: '6" - 6.5"',
    imageUrl: SamsungGalaxyA06,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['4GB'],
    screenResolution: 'FHD+',
    releaseYear: 2021
  },
  {
    id: 'samsung-03',
    name: 'Samsung Galaxy A13',
    brand: 'Samsung',
    price: 83,
    primaryCamera: '49MP - 108MP',
    features: ['Fast charging', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'over 6.5"',
    imageUrl: SamsungGalaxyA13,
    isNew: false,
    dimensions: 'standard',
    storage: ['32GB', '64GB', '128GB'],
    ram: ['3GB', '4GB', '6GB'],
    screenResolution: '4K',
    releaseYear: 2022
  },
  {
    id: 'samsung-04',
    name: 'Samsung Galaxy A14',
    brand: 'Samsung',
    price: 93,
    primaryCamera: '50MP',
    features: ['5G', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyA14,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['4GB', '6GB'],
    screenResolution: 'HD+',
    releaseYear: 2023
  },
  {
    id: 'samsung-05',
    name: 'Samsung Galaxy A23',
    brand: 'Samsung',
    price: 199,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyA23,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['4GB', '8GB'],
    screenResolution: 'HD+',
    releaseYear: 2022
  },
  {
    id: 'samsung-06',
    name: 'Samsung Galaxy A34',
    brand: 'Samsung',
    price: 286,
    primaryCamera: '48MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyA34,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['6GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'samsung-07',
    name: 'Samsung Galaxy A54',
    brand: 'Samsung',
    price: 179,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 HOURS',
    screenSize: '6 - 6.5"',
    imageUrl: SamsungGalaxyA54,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['6GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'samsung-08',
    name: 'Samsung Galaxy C55',
    brand: 'Samsung',
    price: 286,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyC55,
    isNew: true,
    dimensions: 'Compact',
    storage: ['256GB'],
    ram: ['8GB'],
    screenResolution: 'QHD+',
    releaseYear: 2024
  },
  {
    id: 'samsung-09',
    name: 'Samsung Galaxy F13',
    brand: 'Samsung',
    price: 174,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyF13,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['4GB', '8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'samsung-10',
    name: 'Samsung Galaxy F55',
    brand: 'Samsung',
    price: 311,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyF55,
    isNew: true,
    dimensions: 'Compact',
    storage: ['128GB', '256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2024
  },
  {
    id: 'samsung-11',
    name: 'Samsung Galaxy M05',
    brand: 'Samsung',
    price: 73,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyM05,
    isNew: true,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['4GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  {
    id: 'samsung-12',
    name: 'Samsung Galaxy M13',
    brand: 'Samsung',
    price: 153,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyM13,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['4GB'],
    screenResolution: 'HD+',
    releaseYear: 2022
  },
  {
    id: 'samsung-13',
    name: 'Samsung Galaxy M14',
    brand: 'Samsung',
    price: 87,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyM14,
    isNew: false,
    dimensions: 'Standard',
    storage: ['64GB'],
    ram: ['4GB'],
    screenResolution: 'HD+',
    releaseYear: 2023
  },
  {
    id: 'samsung-14',
    name: 'Samsung Galaxy M15',
    brand: 'Samsung',
    price: 144,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: '6 - 6.5"',
    imageUrl: SamsungGalaxyM15,
    isNew: true,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['4GB', '8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'samsung-15',
    name: 'Samsung Galaxy M23',
    brand: 'Samsung',
    price: 299,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyM23,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['4GB', '6GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'samsung-16',
    name: 'Samsung Galaxy M55',
    brand: 'Samsung',
    price: 279,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyM55,
    isNew: true,
    dimensions: 'Compact',
    storage: ['256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2024
  },
  {
    id: 'samsung-17',
    name: 'Samsung Galaxy M35',
    brand: 'Samsung',
    price: 201,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyM35,
    isNew: true,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['6GB', '8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  },
  {
    id: 'samsung-18',
    name: 'Samsung Galaxy S20 FE',
    brand: 'Samsung',
    price: 285,
    primaryCamera: '12MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: '6 - 6.5"',
    imageUrl: SamsungGalaxyS20FE,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['6GB', '8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2020
  },
  {
    id: 'samsung-19',
    name: 'Samsung Galaxy S23 FE',
    brand: 'Samsung',
    price: 272,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: '6 - 6.5"',
    imageUrl: SamsungGalaxyS23FE,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'samsung-20',
    name: 'Samsung Galaxy S23 Ultra',
    brand: 'Samsung',
    price: 597,
    primaryCamera: '200MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyS23Ultra,
    isNew: false,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: '4K',
    releaseYear: 2023
  },
  {
    id: 'samsung-21',
    name: 'Samsung Galaxy S24',
    brand: 'Samsung',
    price: 400,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6 - 6.5"',
    imageUrl: SamsungGalaxyS24,
    isNew: true,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['8GB', '12GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  {
    id: 'samsung-22',
    name: 'Samsung Galaxy S24 FE',
    brand: 'Samsung',
    price: 425,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyS24FE,
    isNew: true,
    dimensions: 'Standard',
    storage: ['128gb'],
    ram: ['8gb'],
    screenResolution: 'QHD+',
    releaseYear: 2024
  },
  {
    id: 'samsung-23',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    price: 719,
    primaryCamera: '200MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Over 48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyS24Ultra,
    isNew: true,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  {
    id: 'samsung-24',
    name: 'Samsung Galaxy S24 Plus',
    brand: 'Samsung',
    price: 574,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyS24plus,
    isNew: true,
    dimensions: 'Large',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  {
    id: 'samsung-25',
    name: 'Samsung Galaxy Z Flip 4',
    brand: 'Samsung',
    price: 449,
    primaryCamera: '12MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Up to 24 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyZFlip4,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2022
  },
  {
    id: 'samsung-26',
    name: 'Samsung Galaxy Z Flip 5',
    brand: 'Samsung',
    price: 399,
    primaryCamera: '12MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Up to 24 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyZFlip5,
    isNew: false,
    dimensions: 'Standard',
    storage: ['256GB'],
    ram: ['8GB'],
    screenResolution: 'QHD+',
    releaseYear: 2023
  },
  {
    id: 'samsung-27',
    name: 'Samsung Galaxy Z Flip 6',
    brand: 'Samsung',
    price: 681,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: 'Up to 24 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyZFlip6,
    isNew: true,
    dimensions: 'Compact',
    storage: ['256GB'],
    ram: ['12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2024
  },
  {
    id: 'samsung-28',
    name: 'Samsung Galaxy Z Fold 4',
    brand: 'Samsung',
    price: 698,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyZFold4,
    isNew: false,
    dimensions: 'Compact',
    storage: ['256GB', '512GB'],
    ram: ['12GB'],
    screenResolution: 'QHD+',
    releaseYear: 2022
  },
  {
    id: 'samsung-29',
    name: 'Samsung Galaxy Z Fold 5',
    brand: 'Samsung',
    price: 1346,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyZFold5,
    isNew: false,
    dimensions: 'Large',
    storage: ['256GB', '512GB'],
    ram: ['12GB'],
    screenResolution: '4K',
    releaseYear: 2023
  },
  {
    id: 'samsung-30',
    name: 'Samsung Galaxy Z Fold 6',
    brand: 'Samsung',
    price: 1244,
    primaryCamera: '50MP',
    features: ['5G', 'Wireless charging', 'Fast charging', 'Water resistant', 'Dual SIM'],
    batteryLife: '24-48 hours',
    screenSize: 'Over 6.5"',
    imageUrl: SamsungGalaxyZFold6,
    isNew: true,
    dimensions: 'Large',
    storage: ['256GB', '512GB'],
    ram: ['12GB'],
    screenResolution: '4K',
    releaseYear: 2024
  },
  // Motorola Phones
  {
    id: 'motorola-edge-40-pro-001',
    name: 'Motorola Edge 40 Pro',
    brand: 'Motorola',
    price: 699,
    primaryCamera: '50MP',
    features: ['5G', 'Water resistant'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: MotorolaEdge40Pro,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB', '256GB', '62GB'],
    ram: ['8GB', '16GB', '32GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'motorola-edge-40-001',
    name: 'Motorola Edge 40',
    brand: 'Motorola',
    price: 549,
    primaryCamera: '50MP',
    features: ['5G'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: MotorolaEdge40,
    isNew: false,
    dimensions: 'Standard',
    storage: ['128GB', '256GB', '62GB'],
    ram: ['8GB'],
    screenResolution: 'FHD+',
    releaseYear: 2023
  },
  {
    id: 'motorola-razr-40-001',
    name: 'Motorola Razr 40',
    brand: 'Motorola',
    price: 599,
    primaryCamera: '64MP',
    features: ['5G'],
    batteryLife: 'Up to 24 hours',
    screenSize: '6" - 6.5"',
    imageUrl: MotorolaRazr40,
    isNew: true,
    dimensions: 'Compact',
    storage: ['128GB', '256GB'],
    ram: ['8GB', '16GB'],
    screenResolution: 'FHD+',
    releaseYear: 2024
  }
];

export const generateMockPhones = (): Phone[] => {
  return MOCK_PHONES;
};